[project]
name = "mychess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chess>=1.11.1",
    "numpy>=2.2.2",
    "open-spiel>=1.5",
]
